# -*- coding: utf-8 -*-
"""CitizenAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tzFNhHZzAq14P0eZsUgl1ZBE2m_Ogacz
"""

!pip install streamlit

import streamlit as st
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM


# Load model and tokenizer
model_name = "ibm-granite/granite-3.2-2b-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto" if torch.cuda.is_available() else None
)

if tokenizer.pad_token is None:
  tokenizer.pad_token = tokenizer.eos_token

def generate_response(prompt, max_length=512):
  inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512)

  if torch.cuda.is_available():
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

  with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_length=max_length,
        temperature=0.4,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id
    )

  response = tokenizer.decode(outputs[0], skip_special_tokens=True)
  response = response.replace(prompt, "").strip()
  return response

def concept_explanation(concept):
  prompt = f"Explain the concept of {concept} in detail with examples:"
  return generate_response(prompt, max_length=800)

def quiz_generator(concept):
  prompt = f"Generate 5 quiz questions about {concept} with different question types (multiple choice, true/false, short answer). At the end, provide all the answer in a separate:"
  return generate_response(prompt, max_length=1000)

# Streamlit UI
st.title(" Educational AI Assistant")

tab1, tab2 = st.tabs(["Concept Explanation", "Quiz Generator"])

with tab1:
  concept_input = st.text_input("Enter a concept", placeholder="e.g., machine learning")
  if st.button("Explain"):
    if concept_input.strip():
      with st.spinner("Generating explanation..."):
        explanation = concept_explanation(concept_input)
      st.text_area("Explanation", explanation, height=250)
    else:
      st.warning("Please enter a concept.")

with tab2:
  quiz_input = st.text_input("Enter a topic", placeholder="e.g., physics")
  if st.button("Generate Quiz"):
    if quiz_input.strip():
      with st.spinner("Generating quiz..."):
        quiz = quiz_generator(quiz_input)
      st.text_area("Quiz Questions", quiz, height=400)
    else:
      st.warning("Please enter a topic.")